---
- name: Provisioning machine
  hosts: "{{ target_host | default('localhost') }}"
  connection: local
  roles:
    - os-config
    - os-packages
    - pip-packages
    # - dotfiles
    - chrome
    - virtualbox
    - keybase
