---
- name: Check if Chrome is installed
  shell: dpkg-query --show google-chrome-stable || true
  register: chrome_check
  changed_when: false

- include: install.yml
  when: "'no packages found matching' in chrome_check.stderr"
