---
- name: Install repository key
  apt_key:
    url: "{{ vbox_repo_key_url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg

- name: Configure repository
  apt_repository:
    repo: "{{ vbox_repo_line }}"
    filename: "{{ vbox_repo_file }}"
    state: present
    update_cache: yes

- name: Install Virtualbox
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop:
    - virtualbox-{{ vbox_version_major }}

- name: Add user to 'vboxusers' group
  user:
    name: "{{ vbox_user | default(lookup('env', 'USER')) }}"
    groups: vboxusers
    append: yes

- name: Check if extension pack is installed
  shell: vboxmanage list extpacks | grep '^Version:.*{{ vbox_extpack_version }}$'
  register: vbox_check_extpack
  failed_when: vbox_check_extpack.rc > 1
  changed_when: false

- name: Download extension pack
  get_url:
    url: "{{ vbox_extpack_url }}"
    dest: "{{ vbox_extpack_dl_file }}"
  when: vbox_check_extpack.rc == 1

- name: Install extension pack
  shell: echo yes | vboxmanage extpack install --replace {{ vbox_extpack_dl_file }}
  when: vbox_check_extpack.rc == 1
